repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-merge-conflict
    - id: check-yaml
      args: [--unsafe]
-   repo: https://github.com/frostming/fix-future-annotations
    rev: 0.5.0  # a released version tag
    hooks:
      - id: fix-future-annotations
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    - id: python-use-type-annotations
    - id: text-unicode-replacement-char
- repo: https://github.com/myint/docformatter
  rev: v1.7.5
  hooks:
    - id: docformatter
      args:
      - --in-place
      - --wrap-summaries=120
      - --wrap-descriptions=120
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
        - id: blacken-docs
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
        - id: ruff-format
        - id: ruff
          args:
            - --fix
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies:
            - pytest-mypy
